# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Run install 
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command

    # - name: Run test
    #   uses: borales/actions-yarn@v4
    #   with:
    #     cmd: test # will run `yarn test` command

    # - name: Run build
    #   uses: borales/actions-yarn@v4
    #   with:
    #     cmd: build:prod # will run `yarn build` command
